<html>
    <head>
        <meta charset="utf-8"/>
        <title>NEW COLLEGE MODULE</title>
        <link rel="icon" href="images/LOGOFINAL.png" type="image/png">
        <link type="text/css" rel="stylesheet" href="materialize-v0.97.0/materialize/css/materialize.min.css" media="screen, projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        
        <style>
            body{
                font-family: "Roboto", sans-serif;
            }
        </style>
    </head>
    <body>
        <script type="text/javascript" src="ckeditor/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" src="jq/jquery-1.11.3.min.js"></script>
        <script type="text/javascript" src="materialize-v0.97.0/materialize/js/materialize.min.js"></script>
        
        <button class="btn modal-trigger" data-target="adddean">ADD Dean</button>
        <a class="waves-effect waves-light btn modal-trigger" href="#adddean">ADD Dean &lt;a&gt;</a>
        
        <div id="adddean" class="modal modal-fixed-footer">
            <div class="modal-content">
                <h5 style="border-bottom: 2px solid #f1f1f1; margin-bottom: 20px;">Add college head</h5>
                <div class="row">
                    <form class="col s12">
                        <div class="row">
                            <div class="input-field col s3">
                                <select>
                                  <option value="1">Dean</option>
                                  <option value="2">Chairperson</option>
                                  <option value="3">OIC-Dean</option>
                                  <option value="4">OIC-Chairperson</option>
                                  <option value="5">Mr.</option>
                                  <option value="6">Mrs.</option>
                                  <option value="7">Ms.</option>
                                </select>
                                <label>Position/Designation</label>
                            </div>
                            <div class="input-field col s4">
                                <input id="last_name" type="text" class="validate">
                                <label for="last_name">Last Name</label>
                            </div>
                            <div class="input-field col s5">
                                <input id="first_name" type="text" class="validate">
                                <label for="first_name">First Name</label>
                            </div>  
                        </div>
                        <div class="row">
                            <div class="input-field col s4">
                                <input id="title" type="text" class="validate" placeholder="Example: MSIT, PhD, MBA">
                                <label for="title">Title</label>
                            </div>
                            <div class="input-field col s8">
                                <input id="email" type="email" class="validate tooltipped" data-position="bottom" data-delay="50" data-tooltip="An autogenerated password will be sent to this email. Please enter a valid email.">
                                <label for="email">Email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s8">
                                <select id="colleges">
                                  <option value="1"></option>
                                  <option value="2">College of Maritime Education &amp; Training</option>
                                  <option value="3">College of Engineering</option>
                                  <option value="4">College of Computer Studies</option>
                                  <option value="5">College of Business &amp; Accountancy</option>
                                </select>
                                <label for="colleges">College</label>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancel</a>
                <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Add</a>
            </div>
        </div>
        
        <script>
            $(document).ready(function(){
                $('.tooltipped').tooltip({delay: 50});
                $('.modal-trigger').leanModal({
                    dismissible: false,
                    opacity: .5, 
                    in_duration: 300, 
                    out_duration: 200, 
                    }                         
                );
                $('select').material_select();
              });
        </script>
    </body>
</html>